# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gte-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gtelwifiue gtesqltespr gt510wifi,$(TARGET_DEVICE)),)

endif
